### ISSUE TITLE
Is it possible to set custom font size?

### ISSUE THREAD

**Issue by mnesarco** [Megabyteceer/blocks-highlighter#5]
Hello Vasiliy,
Thank you for this extension, I was looking exactly for this. I am using it with c++ code:

![ss](https://user-images.githubusercontent.com/1087317/132711974-ce9d477d-45e4-4b0d-bcfc-b1a5a2606ce6.png)

Is it possible to customize the font size for the entire block? the https://code.visualstudio.com/api/references/vscode-api#DecorationRenderOptions does not show a fontSize option.

**Comment by Megabyteceer** [comment]
Try css injection. "textDecoration": ";font-size:200%"

**Comment by mnesarco** [comment]
It worked. Thank you.

**Comment by mnesarco** [comment]
Changing font size with css injection worked great for visualization, but seleccion and cursor position gets screwed up :D

**Comment by Megabyteceer** [comment]
I think thats why no font size feature here. : ) Really handle with text selection with no equal letters size is a big overhead.
