### ISSUE TITLE
Support for single line blocks?

### ISSUE THREAD

**Issue by mnesarco** [Megabyteceer/blocks-highlighter#6]
Hi Vasiliy, is is possible to highlight single line comments?

```
// ~~ Single line comment
```
 
Currently I need to add two more lines to make it work:

```
// ~~
//  Single line comment
// ~
```

Cheers,
Frank.

**Comment by Megabyteceer** [comment]
Hi, sorry for delay. I just published v1.2.0 with single line blocks. Just remove "end" RegExp seting or make it empty or equal to "begin".

**Comment by mnesarco** [comment]
Thank you.

On thing: Single line block style leaks to the next line:

![screenshot_8](https://user-images.githubusercontent.com/1087317/133095883-85f4b43b-73a3-4a55-9da3-a0aa6daa8a2d.png)

```json
    "blockshighlighter.blocks": [
        {
            "fileType": "\\.hpp$|\\.cpp$",
            "begin": "^// \\+~",
            "decorationRenderOptions": {
                "isWholeLine": true,
                "backgroundColor": "#ffffff0f",
                "color": "#ffffff50"
            }
        },
        

```

**Comment by Megabyteceer** [comment]
Just tried the same settings. Looks fine. Sometime vscode has temporary artefacts with decorators.

![image](https://user-images.githubusercontent.com/5096541/133104135-cd3377aa-d5de-4653-b5ff-f11819f1ed21.png)

**Comment by mnesarco** [comment]
Thank you. Yes it worked after a vscode restart (microsoft product :D)

**Comment by mnesarco** [comment]
Single blocks highlight with some fancy regexps and a bit of css injection are very powerful:

![screenshot_9](https://user-images.githubusercontent.com/1087317/133115926-f80e862b-c53b-4414-965f-a18dc70add44.png)

```json
    "blockshighlighter.blocks": [
        {
            "fileType": "\\.hpp$|\\.cpp$",
            "begin": "^\\s*(\\w+):\\s*(//.*)?$",
            "decorationRenderOptions": {
                "isWholeLine": true,
                "backgroundColor": "#0000000f; border-bottom: 1px dashed #ffffff50",
                "color": "#ffffffe0",
            }
        },
   ]
```

**Comment by Megabyteceer** [comment]
Looks amazing : )
Is vscode good with c++?  Is debugging , breakpoints, watching of variables fine? and compilation? last time i used MSVS it was terrible with c++. Im coutrious if vscode is not the same.

**Comment by mnesarco** [comment]
I am quite happy with it, I use linux mint, vscode, clang 12, vscode-clangd, lldb, cmake, ...

Debug: breakpoints, var watching, etc.. works ok
Autocomplete: works
Navigate to definition: works most of the time
Cmake: works
Refactoring: so so
clang-format: works
clang-tidy: works

And with your extension, now I have very enhanced custom syntax coloring
